version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
    - ./db_data:/var/lib/postgresql/data
    ports:
        - 5432:5432
#  pgadmin:
#    image: dpage/pgadmin4
#    restart: always
#    depends_on:
#    - postgres
#    ports:
#    - 5050:80
#    ## you can change pgAdmin default username/password with below environment variables
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "${SUPERUSER_EMAIL}"
#      PGADMIN_DEFAULT_PASSWORD: "${SUPERUSER_PASSWORD}"
volumes:
  db_data:
